# Generated by Django 6.0.3 on 2026-05-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='hostpital_name',
            new_name='hospital_name',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('radiologist', 'Radiologist')], max_length=20),
        ),
    ]
