# Generated by Django 6.0.3 on 2026-05-04 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='addres',
            new_name='address',
        ),
    ]
