# Generated by Django 6.0.3 on 2026-04-02 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('xray', 'X-Ray'), ('mri', 'MRI'), ('ct', 'CT Scan')], max_length=20)),
                ('scan_image', models.ImageField(upload_to='scans/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('ai_condition', models.CharField(blank=True, max_length=255)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('ai_severity', models.CharField(blank=True, max_length=255)),
                ('ai_findings', models.JSONField(default=list)),
                ('ai_bbox', models.JSONField(default=list)),
                ('annotated_image', models.ImageField(blank=True, upload_to='annotated_scans/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='patients.patient')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
