# Generated by Django 6.0.3 on 2026-04-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='scan_image',
            field=models.ImageField(upload_to='scans/%Y/%m/%d/'),
        ),
    ]
