# Generated by Django 6.0.3 on 2026-04-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_alter_scan_scan_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='ai_fracture_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scan',
            name='ai_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='ai_recommendation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
