import React, { useState, useEffect } from 'react';
import { FileText, Download, Printer, X, Eye, Loader2 } from 'lucide-react';
import toast from 'react-hot-toast';
import { getReports } from '../api/reports';

const mockReports = [
    { id: 'REP-1045', patient: 'Rahul Sharma', scanType: 'X-Ray', condition: 'Forearm Fracture', date: '12 Apr 2026, 10:45 AM', generatedBy: 'Dr. Anjali Desai', text: "MEDVISION AI DIAGNOSTIC REPORT\n==============================\nPatient: Rahul Sharma\nDate: 12 Apr 2026, 10:45 AM\nScan ID: 7\n\nCLINICAL INDICATION\nPatient presented with pain and swelling. Requested evaluation for potential fracture.\n\nTECHNIQUE\nStandard two-view X-ray.\n\nFINDINGS\n- Clear fracture line visible at mid-shaft\n- Cortical disruption present\n- Soft tissue swelling observed\n\nIMPRESSION\nForearm Fracture detected at Left forearm mid-shaft with 87% confidence.\n\nRECOMMENDATION\nOrthopedic consultation required immediately\n" },
    { id: 'REP-1044', patient: 'Vikram Desai', scanType: 'CT Scan', condition: 'Pleural Effusion', date: '08 Apr 2026, 12:00 PM', generatedBy: 'System AI', text: "Mock report text..." },
    { id: 'REP-1043', patient: 'Ananya Singh', scanType: 'MRI', condition: 'Normal', date: '05 Apr 2026, 03:20 PM', generatedBy: 'Dr. Sharma', text: "Mock report text..." }
];

const Reports = () => {
    const [selectedReport, setSelectedReport] = useState(null);
    const [reports, setReports] = useState([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const fetchReports = async () => {
            try {
                const data = await getReports();
                setReports(data.length > 0 ? data : mockReports);
            } catch (err) {
                console.warn('API getReports failed, using mock data');
                setReports(mockReports);
            } finally {
                setLoading(false);
            }
        };
        fetchReports();
    }, []);

    const handleDownload = (report) => {
        const blob = new Blob([report.text], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `Report_${report.id}.txt`;
        a.click();
        URL.revokeObjectURL(url);
        toast.success(`Downloaded ${report.id}`);
    };

    const handlePrint = () => {
        window.print();
    };

    return (
        <div className="space-y-6 relative">
            <h1 className="text-2xl font-bold text-gray-800 mb-6">Generated Reports</h1>

            <div className="medical-card">
                <div className="overflow-x-auto">
                    <table className="w-full text-sm text-left">
                        <thead className="text-xs text-gray-500 uppercase bg-gray-50 border-b border-[#E2E8F0]">
                            <tr>
                                <th className="px-6 py-4 font-medium">Report ID</th>
                                <th className="px-6 py-4 font-medium">Patient</th>
                                <th className="px-6 py-4 font-medium">Scan Type</th>
                                <th className="px-6 py-4 font-medium">Condition</th>
                                <th className="px-6 py-4 font-medium">Generated By</th>
                                <th className="px-6 py-4 font-medium">Date</th>
                                <th className="px-6 py-4 font-medium text-right">Actions</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-gray-100">
                            {reports.map(report => (
                                <tr key={report.id} className="hover:bg-gray-50 transition-colors">
                                    <td className="px-6 py-4 font-mono text-gray-600">{report.id}</td>
                                    <td className="px-6 py-4 font-medium text-gray-900">{report.patient || report.patient_name || 'Unknown'}</td>
                                    <td className="px-6 py-4 text-gray-600">
                                        <span className="bg-gray-100 text-gray-700 px-2 py-1 rounded text-xs truncate max-w-[100px]">{report.scanType || report.scan_type || 'Unknown'}</span>
                                    </td>
                                    <td className="px-6 py-4 text-gray-800 font-medium">{report.condition}</td>
                                    <td className="px-6 py-4 text-gray-600">{report.generatedBy || report.generated_by || 'System'}</td>
                                    <td className="px-6 py-4 text-gray-500">{report.date}</td>
                                    <td className="px-6 py-4 text-right space-x-2">
                                        <button
                                            onClick={() => setSelectedReport(report)}
                                            className="inline-flex items-center justify-center w-8 h-8 rounded-lg bg-blue-50 text-blue-600 hover:bg-blue-100 transition-colors"
                                            title="View Report"
                                        >
                                            <Eye className="w-4 h-4" />
                                        </button>
                                        <button
                                            onClick={() => handleDownload(report)}
                                            className="inline-flex items-center justify-center w-8 h-8 rounded-lg bg-green-50 text-green-600 hover:bg-green-100 transition-colors"
                                            title="Download text file"
                                        >
                                            <Download className="w-4 h-4" />
                                        </button>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </div>

            {/* Report Viewer Modal */}
            {selectedReport && (
                <div className="fixed inset-0 bg-black bg-opacity-50 z-50 flex items-center justify-center p-4 backdrop-blur-sm print:absolute print:inset-0 print:bg-white print:z-auto print:block">
                    <div className="bg-white rounded-2xl w-full max-w-3xl max-h-[90vh] flex flex-col shadow-2xl animate-in fade-in zoom-in duration-200 print:shadow-none print:w-full print:max-w-none print:h-auto">

                        <div className="bg-gray-50 border-b border-[#E2E8F0] px-6 py-4 flex justify-between items-center rounded-t-2xl print:hidden">
                            <div className="flex items-center">
                                <div className="bg-primary p-2 rounded-lg text-white mr-3">
                                    <FileText className="w-5 h-5" />
                                </div>
                                <div>
                                    <h2 className="text-lg font-bold text-gray-900">{selectedReport.id}</h2>
                                    <p className="text-sm text-gray-500">{selectedReport.patient} • {selectedReport.date}</p>
                                </div>
                            </div>

                            <div className="flex space-x-2">
                                <button onClick={handlePrint} className="btn-outline px-3 py-1.5 h-9">
                                    <Printer className="w-4 h-4 mr-2" /> Print
                                </button>
                                <button onClick={() => handleDownload(selectedReport)} className="btn-primary px-3 py-1.5 h-9">
                                    <Download className="w-4 h-4 mr-2" /> Save
                                </button>
                                <div className="w-px h-9 bg-gray-300 mx-1"></div>
                                <button onClick={() => setSelectedReport(null)} className="p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded-lg">
                                    <X className="w-5 h-5" />
                                </button>
                            </div>
                        </div>

                        <div className="p-8 overflow-y-auto print:p-0 print:overflow-visible">
                            <div className="hidden print:block mb-8 border-b-2 border-black pb-4">
                                <h1 className="text-3xl font-bold">MEDVISION AI</h1>
                                <p className="text-lg text-gray-600 mt-1">Official Diagnostic Report</p>
                            </div>
                            <pre className="whitespace-pre-wrap font-mono text-sm leading-relaxed text-gray-900">
                                {selectedReport.text}
                            </pre>
                            <div className="hidden print:block mt-24 pt-8 border-t border-gray-300">
                                <div className="flex justify-between">
                                    <div>
                                        <p className="font-bold">Generated By: {selectedReport.generatedBy}</p>
                                        <p>Date: {selectedReport.date}</p>
                                    </div>
                                    <div className="text-right">
                                        <p className="italic text-gray-500">Sign: ___________________</p>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            )}
        </div>
    );
};

export default Reports;
